apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: developers
  labels:
    access: read
rules:
  - apiGroups:
     - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - watch
  - apiGroups:
     - networking.k8s.io
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch
