apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: developers
  labels:
    access: read
subjects:
  - kind: ServiceAccount
    namespace: default
    name: developer
roleRef:
    kind: ClusterRole
    name: developers
    apiGroup: rbac.authorization.k8s.io
